services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Analytics\:
        resource: '../../src/Analytics/*'
        exclude:
            # domain
            - '../../src/Analytics/Domain/Entity'
            - '../../src/Analytics/Domain/ValueObject'
