services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Experience\:
        resource: '../../src/Experience/*'
        exclude:
            # domain
            - '../../src/Experience/Domain/Entity'
