services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Settings\:
        resource: '../../src/Settings/*'
        exclude:
            # domain
            - '../../src/Settings/Domain/Entity'
