twig_component:
    anonymous_template_directory: component/
    defaults:
        # Namespace & directory for components
        App\GitHub\Ui\Component\: component/
        App\User\Ui\Component\: component/
