controllers_contact:
    resource:
        path: ../../src/Contact/Ui/Controller
        namespace: App\Contact\Ui\Controller
    type: attribute
    prefix: '/contact'
    name_prefix: app_contact_
    trailing_slash_on_root: false

kernel:
    resource: App\Shared\Infrastructure\Kernel
    type: attribute
